# _______               _ _
# |__   __|        /\   | | |
#    | |_ __      /  \  | | |
#    | | '_ \    / /\ \ | | |
#    | | |_) |  / ____ \| | |
#  _ |_| .__/  /_/    \_\_|_| _              _            __ ___
# | |  | |          /\       | |            | |          /_ |__ \
# | |__|_|   _     /  \   ___| |__   ___  __| | ___  _ __ | |  ) |
# | '_ \| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
# |_.__/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|
#         __/ |
#        |___/


# Time can be a numeric value or "none"
# please respect the configuration
Timetotp: 2
TeleportMessagePrefix: §c[§eTpAll§c]
MessageBeforeTeleportation: avant teleportation